mode: openssl

certs_dir: ../certs

openssl:
  dir: /opt/ossl-3.5
  command: ""
  conf_path: openssl/openssl.cnf

x509:
  root_cert_path: root.crt
  chain_path: chain.pem
  client_cert_path: client.crt
  server_cert_path: server.crt

keys:
  # Server encrypts to client using client KEM public key; server decrypts using server KEM private key.
  kem_public_path: openssl/client.kem.pub
  kem_private_path: openssl/server.kem.key

  # Server signs using server Sig private key.
  # Peer Sig public key can be omitted in OpenSSL mode; it will be extracted from client_cert_path.
  sig_private_path: openssl/server.sig.key
  sig_public_path: ""

listen: 127.0.0.1:5000
upstream: http://127.0.0.1:5500

replay_ttl_seconds: 120
replay_max_entries: 200000
